### ISSUE TITLE
Packagist Integration/Webhook not working

### ISSUE THREAD

**Issue by zsturgess** [partnermarketing/FileSystemBundle#30]
https://packagist.org/packages/partnermarketing/file-system-bundle is still stuck on v2.0.

There should be a webhook/integration that is updating packagist automatically.

**Comment by BernardoSilva** [comment]
I checked packagist and everything seam to be ok there.
I've updated the repo UP setting on packagist because I think it needs to be case sensitive, but it updated right after.

Let's leave this open until we do the next release and check if the web-hook is working correctly or not. :)

In meanwhile, new version available.
https://packagist.org/packages/partnermarketing/file-system-bundle#3.0.1

**Comment by EmilyShepherd** [comment]
Closing as this hook is working properly now :+1:
